- name: Generate the snake files
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: darligi
          color: Pacman
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
